# Generated by Django 5.0.4 on 2025-04-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerecord',
            name='patient_name',
        ),
    ]
