# Generated by Django 5.2.6 on 2025-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Cancel Reason'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Is Canceled'),
        ),
    ]
