# Generated by Django 5.2.6 on 2025-09-27 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_paymenttype_cancel_reason_paymenttype_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTypeCanceled',
            fields=[
            ],
            options={
                'verbose_name': 'Canceled Payment Type',
                'verbose_name_plural': 'Canceled Payment Types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.paymenttype',),
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
